### ISSUE TITLE
index.php redirect issue

### ISSUE THREAD

**Issue by volodymyrdovhan** [emeneo/moodle-local_courselist#2]
Hello,

please use the default moodle redirect() function for redirecting. 
I got an error when try accessing index.php page directly:

![image](https://github.com/user-attachments/assets/100a549d-e396-4125-8ad8-e83f694b8934)

**Comment by Flottertotte** [comment]
Hi, thanks for reporting this. This problem is fixed. As the index file is not intended to be visited directly, it redirects to root in case it is. Now, only moodle functions are used and some security improvements have been added.
