### ISSUE TITLE
Not all strings defined in language files

### ISSUE THREAD

**Issue by volodymyrdovhan** [emeneo/moodle-local_courselist#3]
Hello,

I found plain strings in English:

![image](https://github.com/user-attachments/assets/a1ad6db1-ba0b-49a6-912f-8528642f050a)

**Comment by Flottertotte** [comment]
Thanks for reporting this. It is fixed now.

**Comment by volodymyrdovhan** [comment]
Hello,
one more global css selector should be removed:
![image](https://github.com/user-attachments/assets/162e14c3-8c4a-422c-8818-cc55187d4f0e)
